name: Periodic Maintenance

on:
  schedule:
    - cron: '0 0 * * *'  # Schedule daily at midnight UTC

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      
      - name: Run Cleanup Script
        run: |
          rm -rf ./temp
          npm cache clean --force
